<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Browser</name>
   <tag></tag>
   <elementGuidId>91c0b69e-5bf6-4fb0-bd53-c2bc50317e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bootstrap'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(60)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e73d33c7-747c-4cda-b55d-63f4fabcc051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser</value>
      <webElementGuid>789f29d2-02d1-4c59-8651-5d0cdb9e843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[60]</value>
      <webElementGuid>1eb7b41f-ad0d-4917-98b4-554dbeedffec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>7940222c-10ee-4835-8233-ec7a6aa187d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bootstrap'])[1]/following::li[1]</value>
      <webElementGuid>ce0716b5-8507-4a2f-af2f-b7274df88d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BooleanCoercer'])[1]/following::li[2]</value>
      <webElementGuid>67ee495b-19fe-4ab2-85b9-18afbe154b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BrowserContextID'])[1]/preceding::li[1]</value>
      <webElementGuid>b81ffab9-8663-4984-9230-1f82587dc916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[60]</value>
      <webElementGuid>426aeac5-fb4b-4489-9d50-2827f047b4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Browser' or . = 'Browser')]</value>
      <webElementGuid>29ffc881-c16a-413f-8df2-2df6fb4b17ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
