<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Browser</name>
   <tag></tag>
   <elementGuidId>fb4facab-ad38-4ff0-b275-a212accf7c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bootstrap'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(60) > a[title=&quot;interface in org.openqa.selenium.remote&quot;] > span.interfaceName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c718f7c-dca2-4970-a6b3-c8d9df709503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>interfaceName</value>
      <webElementGuid>e100b129-6aa6-4f9f-aed1-44a3f3c6321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser</value>
      <webElementGuid>38dd70e9-0f52-45c2-a48e-d7363f2b5955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[60]/a[1]/span[@class=&quot;interfaceName&quot;]</value>
      <webElementGuid>f17f760c-6a5d-47a3-be67-1e6855ff6dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>1763dbcb-afaf-4850-87cc-08d0dbad6573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bootstrap'])[1]/following::span[1]</value>
      <webElementGuid>2839ea87-74b2-4edb-a401-f3da35b90708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BooleanCoercer'])[1]/following::span[1]</value>
      <webElementGuid>6d8992fe-69ce-4199-9140-d44560a16e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BrowserContextID'])[1]/preceding::span[1]</value>
      <webElementGuid>a9d75fb0-da36-481f-a568-19929bc60ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BrowsingContext'])[1]/preceding::span[1]</value>
      <webElementGuid>354946c8-5eed-4e3c-a20c-d5befd2cae52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browser']/parent::*</value>
      <webElementGuid>2f765e68-937c-4ad1-872f-433682773a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[60]/a/span</value>
      <webElementGuid>6e3a1a36-a203-4561-ab59-b3223957cbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Browser' or . = 'Browser')]</value>
      <webElementGuid>dfbc0334-d4f9-4345-a833-670d99d0fe9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
